import type { Metadata } from 'next'
import './globals.css'
import Topbar from '@/components/Topbar'



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen w-screen bg-white text-black flex justify-center">
          <div className="w-full max-w-[1000px] grid grid-rows-[70px_1fr]">
            <Topbar />
            {children}
          </div>
      </body>
    </html>
  )
}
